### ISSUE TITLE
生成Wrap文件报错：error CS0122: 'Utils' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by ViSDK** [chexiongsheng/puerts_unity_demo#1]
Wrap文件内的函数 基本都会调用 Puerts.Utils.GetSelf， 而此时 Utils 是非 public 的， 所以报错

**Comment by chexiongsheng** [comment]
你把puerts核心代码放别的程序集了？

**Comment by ViSDK** [comment]
是的，放到 Plugins 下面了，因为我觉得JS引擎属于插件，应该到Assembly-CSharp-firstpass

**Comment by chexiongsheng** [comment]
那你把Util改成public，看看还有其它错误不？我一并改

**Comment by ViSDK** [comment]
嗯，我本地把Utils改成public ,错误解决了，暂时未发现其他错误

**Comment by chexiongsheng** [comment]
我改了

**Comment by ViSDK** [comment]
OK, 谢谢
