### ISSUE TITLE
多线程实例

### ISSUE THREAD

**Issue by yuatpocketgems** [chexiongsheng/puerts_unity_demo#18]
看到JsEnv中有THREAD_SAFE宏。启用后测试了一下从C#异步调用JS代码，结果出现崩溃。

```csharp
Task.Run(() => {
  genericDelegate.Action();
}).Wait();
```

崩溃信息提到`undefined:0: Max stack limit reached`.

同一个action在主线程调用运行正常
```csharp
genericDelegate.Action();
```

可不可以出一个多线程的实例？

**Comment by Sea4U** [comment]
是可以在不同的线程开启虚拟机,而不是不同线程调用
