### ISSUE TITLE
DllNotFoundException: puerts

### ISSUE THREAD

**Issue by setsuodu** [chexiongsheng/puerts_unity_demo#21]
DllNotFoundException: puerts
Puerts.JsEnv..ctor (Puerts.ILoader loader, System.Int32 debugPort, Puerts.JsEnvMode mode, System.IntPtr externalRuntime, System.IntPtr externalContext) (at Assets/Puerts/Src/JsEnv.cs:79)
Puerts.JsEnv..ctor (Puerts.JsEnvMode mode) (at Assets/Puerts/Src/JsEnv.cs:57)
PuertsTest.JsCallCs.Start () (at Assets/Examples/01_JsCallCs/JsCallCs.cs:12)

2018LTS，MacOS，运行、生成都报错。

**Comment by chexiongsheng** [comment]
试试把Assets/Plugins/macOS/libpuerts.bundle移动到上一层目录（Assets/Plugins/）

**Comment by zombieyang** [comment]
更新项目后要重启unity，如果还不行，可以在群里找下我。
