### ISSUE TITLE
原来github的lfs带宽是增值服务

### ISSUE THREAD

**Issue by zhaoboqiang** [chexiongsheng/puerts_unity_demo#33]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/chexiongsheng/puerts_unity_demo.git/info/lfs'

**Comment by chexiongsheng** [comment]
@zombieyang 这个commit用lfs来提交库了？：https://github.com/chexiongsheng/puerts_unity_demo/commit/9f114873a6aeaccc625ff5a5926ee62b33d24fab

lfs是有流量限制的，很快就耗尽
