### ISSUE TITLE
Problems opening Demo project

### ISSUE THREAD

**Issue by marwie** [chexiongsheng/puerts_unity_demo#40]
Hello,

I've just wanted to open the project that is now upgraded to the package format (yay) but have some problems and errors that I'd like to address here:

1) When opening the project I'm getting two errors saying there are two puerts.dll's marked as editor dlls:
   !x fgf```Multiple plugins with the same name 'puerts' (found at 'Packages/com.tencent.puerts.core/Runtime/Plugins/x86_64/puerts.dll' and 'Packages/com.tencent.puerts.core/Editor/Plugins/x86_64/puerts.dll'). That means one or more plugins are set to be compatible with Editor. Only one plugin at the time can be used by Editor.```
2) I'm wondering why the ``.meta`` files in the Unity project have not been committet? When opening the project I already have over 60 changed files. Maybe the plugin error is also caused by that. I will look into it now
3) in ``package/Editor/Plugin/x86`` seems to be a missing dll because there is a ``dll.meta`` file that Unity deletes when opening the project 

Console error (1)
![image](https://user-images.githubusercontent.com/5083203/158263136-fae22661-ea9b-402f-874a-17d7acb83a18.png)

Changed files (2)
![image](https://user-images.githubusercontent.com/5083203/158263109-0f7a7d05-6a4e-47f0-9132-43b369271535.png)

Deleted meta (3)
![image](https://user-images.githubusercontent.com/5083203/158263039-dd7f3735-4fe8-48d4-ade3-71c8cbb583ad.png)

**Comment by zombieyang** [comment]
I remove all the package file to test the new `sync package` action and cause this bug... fixed now.

**Comment by zombieyang** [comment]
I made a rollback. recover it later I have all actions finished.
