### ISSUE TITLE
generate code报错

### ISSUE THREAD

**Issue by Ninian4155** [chexiongsheng/puerts_unity_demo#47]
使用demo项目直接generate code报错:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/58923645/162155709-db5402b6-5752-4ba2-9d16-5f31a7709e6c.png">
将demo中的1.3.0版本升级到1.3.2也是一样的情况。
顺便提一句事例06的js代码在05的Resources。
Unity版本：2020.3.14f1

**Comment by Ninian4155** [comment]
补充一下，测试是android平台。

**Comment by zombieyang** [comment]
1.2.x版本有尝试过么，我看这个类似乎没有在https://github.com/chexiongsheng/puerts_unity_demo/blob/master/projects/Puerts_Demo/Assets/Examples/Editor/01_WrapperGenerate/PuertsFilter.cs 中包含。
你应该可以自行在filter中过滤的。
