### ISSUE TITLE
Array.CreateInstance创建string[]实例, 实际类型为object[]

### ISSUE THREAD

**Issue by layerpsr** [chexiongsheng/puerts_unity_demo#6]
测试int丶Class类型正常, 仅发现string[]异常

![image](https://user-images.githubusercontent.com/45587825/93419410-5d9a2500-f8df-11ea-9138-3fa6066b31bf.png)
![image](https://user-images.githubusercontent.com/45587825/93419431-65f26000-f8df-11ea-91f5-26d572aa3484.png)

**Comment by layerpsr** [comment]
使用v5版本

**Comment by chexiongsheng** [comment]
我试了正常

**Comment by chexiongsheng** [comment]
另外，有问题到：https://github.com/Tencent/puerts，提，这只是demo而已，只处理和demo相关的问题。
