### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by yhslai** [chexiongsheng/puerts_unity_demo#65]
Compliation error for the latest version on master branch:

> Assets\Examples\09_Node.js\NodeJS.cs(19,27): error CS7036: There is no argument given that corresponds to the required formal parameter 'isolate' of 'PuertsDLL.GetLibBackend(IntPtr)'

Unity version：2022.3.24f1

**Comment by meilaopo** [comment]
+1

**Comment by Yuki001** [comment]
projects/1_Start_Template/Assets/Samples/Editor/04_NodeTSCAndHotReload/NodeTSCAndHotReload.cs

also use "PuertsDLL.GetLibBackend()" and cause compile errors.
